/**
 * Unified Draft & Research interface for generating emails and statements.
 */

interface PIInfo {
    name: string;
    institution?: string;
    openalex_id?: string;
    orcid?: string;
    summary?: string;
    last_known_institutions?: Array<string | { display_name?: string; name?: string }>;
    affiliated_institutions?: string[];
}

interface Paper {
    title: string;
    year?: number;
    doi?: string;
    url?: string;
    abstract?: string;
    summary: string;
}

interface ClinicalTrial {
    nct_id: string;
    title: string;
    brief_summary?: string;
    detailed_description?: string;
    conditions?: string[];
    interventions?: Array<{ type?: string; name?: string; description?: string }>;
    phase?: string;
    overall_status?: string;
    start_date?: string;
    completion_date?: string;
    enrollment?: number;
    lead_sponsor?: string;
    locations?: string[];
    pi_name?: string;
    alignment_score?: number;
    key_themes?: string[];
    user_experience_matches?: string[];
}

interface NIHProject {
    appl_id?: string;
    fiscal_year?: number;
    project_serial_num?: string;
    organization?: string;
    organization_type?: string;
    award_type?: string;
    activity_code?: string;
    award_amount?: number;
    project_num_split?: string;
    principal_investigators?: string[];
    program_officers?: Array<any>;
    cong_dist?: string;
    project_start_date?: string;
    project_end_date?: string;
    opportunity_number?: string;
    full_study_section?: string;
    award_notice_date?: string;
    core_project_num?: string;
    pref_terms?: string[];
    project_title?: string;
    phr_text?: string;
    spending_categories_desc?: string[];
    search_url?: string;
}

interface PIResearchData {
    pi_info: PIInfo;
    papers: Paper[];
    clinical_trials?: ClinicalTrial[];
    nih_projects?: NIHProject[];
}

interface DraftVersion {
    id: string;
    timestamp: Date;
    format: 'email' | 'statement';
    content: string; // HTML from Summernote
    subject?: string; // For email format
    isGenerated: boolean; // true if generated by AI, false if user draft
    wordCount?: number;
}

let currentProfileId: string | null = null;
let currentPIResearch: PIResearchData | null = null;
let draftVersions: DraftVersion[] = [];
let currentVersionId: string | null = null;
let emailContent: { subject: string; body: string } = { subject: '', body: '' };
let statementContent: string = '';
let currentPapersPage: number = 1;
const papersPerPage: number = 10;
let selectedPapers: Set<number> = new Set();
let selectedTrials: Set<number> = new Set();
let selectedNihProjects: Set<number> = new Set();
let clinicalTrialsCollapsed: boolean = false;
let nihProjectsCollapsed: boolean = false;
let papersCollapsed: boolean = false;

export function renderDraftResearchTab(): void {
    const container = document.getElementById('tab-content-draft-research');
    if (!container) return;

    container.innerHTML = `
        <div class="agents-container" style="max-width: 1600px; margin: 0 auto; padding: 2rem;">
            <h2 style="margin-bottom: 1.5rem;">Draft & Research</h2>
            <p style="margin-bottom: 2rem; color: #666;">Enter PI information to gather research, then generate personalized emails or statements.</p>

            <div class="draft-research-layout">
                <!-- Center Column (Writing Tool - Main Focus) -->
                <div class="draft-center-column">
                    <div class="writing-tool-box" style="background-color: #f8f9fa; border: 2px solid #dee2e6; border-radius: 8px; padding: 2rem;">
                        <div style="display: grid; grid-template-columns: 1fr 3fr; gap: 2rem;">
                            <!-- Left: Version History Timeline -->
                            <div class="version-history-box" style="background-color: #ffffff; border: 1px solid #dee2e6; border-radius: 6px; padding: 1rem;">
                                <h4 style="margin-top: 0; margin-bottom: 1rem; font-size: 1em;">Version History</h4>
                                <div id="version-timeline" style="max-height: 60vh; overflow-y: auto;">
                                    <div style="text-align: center; color: #666; padding: 1rem; font-style: italic; font-size: 0.85em;">
                                        No versions yet. Start writing to see your history.
                                    </div>
                                </div>
                            </div>

                            <!-- Right: Writing Tool Content -->
                            <div>
                                <h3 style="margin-top: 0; margin-bottom: 1rem;">Writing Tool</h3>
                        <div class="format-toggle-section" style="margin-bottom: 1.5rem;">
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Format:</label>
                            <div class="toggle-buttons">
                                <button id="format-email" class="format-toggle active">Email</button>
                                <button id="format-statement" class="format-toggle">Statement</button>
                            </div>
                        </div>

                        <div id="email-options" class="format-options" style="display: block;">
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="email-word-count-target" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Target Word Count</label>
                                <input type="number" id="email-word-count-target" value="300" min="200" max="500" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="email-subject" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Subject</label>
                                <input type="text" id="email-subject" placeholder="Email subject line..." style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                        </div>

                        <div id="statement-options" class="format-options" style="display: none;">
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="statement-word-count-target" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Target Word Count</label>
                                <input type="number" id="statement-word-count-target" value="375" min="250" max="500" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                        </div>

                        <div class="form-group" style="margin-bottom: 1rem;">
                            <label for="draft-editor" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Editor</label>
                            <textarea id="draft-editor" rows="12" placeholder="Start writing..." style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px; font-family: inherit;"></textarea>
                        </div>
                        <div class="word-count" style="margin-bottom: 1rem; font-size: 0.9em; color: #666;">Word count: <span id="word-count-display">0</span></div>

                        <div style="display: flex; gap: 0.5rem; margin-top: 1rem;">
                            <button id="generate-draft-btn" class="btn-primary" disabled style="flex: 1; padding: 0.75rem; font-size: 1rem; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;">Generate Draft</button>
                            <button id="enhance-draft-btn" class="btn-secondary" style="padding: 0.75rem 1rem; background-color: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer;">Enhance Draft</button>
                            <button id="save-version-btn" class="btn-secondary" style="padding: 0.75rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Save Version</button>
                        </div>

                        <div class="export-buttons" style="margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #dee2e6; display: flex; gap: 0.5rem; flex-wrap: wrap;">
                            <button id="copy-btn" class="btn-secondary" style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Copy</button>
                            <button id="gmail-btn" class="btn-secondary" style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Gmail</button>
                            <button id="google-docs-btn" class="btn-secondary" style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Docs</button>
                            <button id="download-txt-btn" class="btn-secondary" style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Download</button>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right Column (PI Information) -->
                <div class="draft-right-column">
                    <div class="pi-information-box" style="background-color: #f8f9fa; border: 2px solid #dee2e6; border-radius: 8px; padding: 1.5rem;">
                        <div class="pi-input-section">
                            <h3 style="margin-top: 0; margin-bottom: 1rem;">PI Information</h3>
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="pi-name" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Name *</label>
                                <input type="text" id="pi-name" placeholder="Dr. Jane Smith" required style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="pi-orcid" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">ORCID (optional)</label>
                                <input type="text" id="pi-orcid" placeholder="0000-0000-0000-0000" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="pi-openalex-id" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">OpenAlex ID (optional)</label>
                                <input type="text" id="pi-openalex-id" placeholder="A123456789" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                            <div class="form-group" style="margin-bottom: 1rem;">
                                <label for="pi-institution" style="display: block; margin-bottom: 0.5rem; font-weight: bold;">Institution (optional)</label>
                                <input type="text" id="pi-institution" placeholder="University Name" style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;">
                            </div>
                            <button id="gather-research-btn" class="btn-primary" style="width: 100%; padding: 0.75rem; font-size: 1rem; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; margin-top: 0.5rem;">Gather Research</button>
                        </div>

                        <div id="pi-summary-section" class="pi-summary-section" style="display: none; margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #dee2e6;">
                            <h3 style="margin-top: 0; margin-bottom: 1rem;">PI Summary</h3>
                            <div id="pi-summary-content"></div>
                        </div>

                        <div id="clinical-trials-section" class="clinical-trials-section" style="display: none; margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #dee2e6;">
                            <h3 style="margin-top: 0; margin-bottom: 1rem; cursor: pointer; user-select: none; display: flex; align-items: center; gap: 0.5rem; font-size: 1.1em; font-family: inherit;" id="clinical-trials-header">
                                <span style="font-size: 0.8em; transition: transform 0.2s;" id="clinical-trials-chevron">▼</span>
                                <span>Clinical Trials</span>
                            </h3>
                            <div id="clinical-trials-list"></div>
                        </div>

                        <div id="nih-projects-section" class="nih-projects-section" style="display: none; margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #dee2e6;">
                            <h3 style="margin-top: 0; margin-bottom: 1rem; cursor: pointer; user-select: none; display: flex; align-items: center; gap: 0.5rem; font-size: 1.1em; font-family: inherit;" id="nih-projects-header">
                                <span style="font-size: 0.8em; transition: transform 0.2s;" id="nih-projects-chevron">▼</span>
                                <span>NIH Projects</span>
                            </h3>
                            <div id="nih-projects-list"></div>
                        </div>

                        <div id="papers-section" class="papers-section" style="display: none; margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #dee2e6;">
                            <h3 style="margin-top: 0; margin-bottom: 1rem; cursor: pointer; user-select: none; display: flex; align-items: center; gap: 0.5rem; font-size: 1.1em; font-family: inherit;" id="papers-header">
                                <span style="font-size: 0.8em; transition: transform 0.2s;" id="papers-chevron">▼</span>
                                <span>Recent Papers</span>
                            </h3>
                            <div id="papers-list"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    `;

    setupDraftResearchListeners();

    // Initialize Summernote editor
    waitForSummernoteAndInitializeDraft();

    // Reset version history
    draftVersions = [];
    currentVersionId = null;
    emailContent = { subject: '', body: '' };
    statementContent = '';

    // Render initial empty timeline
    renderVersionTimeline();
}

function waitForSummernoteAndInitializeDraft(retries = 10): void {
    if (typeof (window as any).jQuery !== 'undefined' && typeof (window as any).jQuery.fn.summernote !== 'undefined') {
        setTimeout(() => {
            initializeDraftEditor();
        }, 100);
    } else if (retries > 0) {
        setTimeout(() => {
            waitForSummernoteAndInitializeDraft(retries - 1);
        }, 200);
    } else {
        console.warn('Summernote or jQuery failed to load');
    }
}

function initializeDraftEditor(): void {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');

    if (!editor) return;

    // Destroy existing instance if any
    if ($(editor).hasClass('summernote-initialized')) {
        $(editor).summernote('destroy');
    }

    $(editor).summernote({
        height: 400,
        minHeight: 200,
        maxHeight: 600,
        placeholder: 'Start writing...',
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ],
        callbacks: {
            onChange: function(contents: string) {
                updateWordCount();
            }
        }
    });
    $(editor).addClass('summernote-initialized');

    // Update word count on initialization
    updateWordCount();
}

function setupCollapsibleSections(): void {
    const clinicalTrialsHeader = document.getElementById('clinical-trials-header');
    const nihProjectsHeader = document.getElementById('nih-projects-header');
    const papersHeader = document.getElementById('papers-header');

    if (clinicalTrialsHeader) {
        clinicalTrialsHeader.addEventListener('click', () => toggleSection('clinical-trials'));
    }

    if (nihProjectsHeader) {
        nihProjectsHeader.addEventListener('click', () => toggleSection('nih-projects'));
    }

    if (papersHeader) {
        papersHeader.addEventListener('click', () => toggleSection('papers'));
    }
}

function toggleSection(sectionName: 'clinical-trials' | 'nih-projects' | 'papers'): void {
    const listId = `${sectionName}-list`;
    const chevronId = `${sectionName}-chevron`;
    const listElement = document.getElementById(listId);
    const chevronElement = document.getElementById(chevronId);

    if (!listElement || !chevronElement) return;

    let isCollapsed: boolean;
    if (sectionName === 'clinical-trials') {
        clinicalTrialsCollapsed = !clinicalTrialsCollapsed;
        isCollapsed = clinicalTrialsCollapsed;
    } else if (sectionName === 'nih-projects') {
        nihProjectsCollapsed = !nihProjectsCollapsed;
        isCollapsed = nihProjectsCollapsed;
    } else {
        papersCollapsed = !papersCollapsed;
        isCollapsed = papersCollapsed;
    }

    if (isCollapsed) {
        listElement.style.display = 'none';
        chevronElement.textContent = '▶';
        chevronElement.style.transform = 'rotate(0deg)';
    } else {
        listElement.style.display = 'block';
        chevronElement.textContent = '▼';
        chevronElement.style.transform = 'rotate(0deg)';
    }
}

function updateWordCount(): void {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const wordCountDisplay = document.getElementById('word-count-display');

    if (!editor || !wordCountDisplay) return;

    if ($(editor).hasClass('summernote-initialized')) {
        const html = $(editor).summernote('code');
        const text = $('<div>').html(html).text();
        const wordCount = text.trim().split(/\s+/).filter((word: string) => word.length > 0).length;
        wordCountDisplay.textContent = wordCount.toString();
    }
}

function setupDraftResearchListeners(): void {
    const gatherBtn = document.getElementById('gather-research-btn');
    const generateBtn = document.getElementById('generate-draft-btn');
    const formatEmailBtn = document.getElementById('format-email');
    const formatStatementBtn = document.getElementById('format-statement');
    const copyBtn = document.getElementById('copy-btn');
    const gmailBtn = document.getElementById('gmail-btn');
    const googleDocsBtn = document.getElementById('google-docs-btn');
    const downloadTxtBtn = document.getElementById('download-txt-btn');
    const refreshSummaryBtn = document.getElementById('refresh-summary-btn');
    const enhanceDraftBtn = document.getElementById('enhance-draft-btn');

    if (gatherBtn) {
        gatherBtn.addEventListener('click', handleGatherResearch);
    }

    if (generateBtn) {
        generateBtn.addEventListener('click', handleGenerateDraft);
    }

    if (enhanceDraftBtn) {
        enhanceDraftBtn.addEventListener('click', handleEnhanceDraft);
    }

    if (formatEmailBtn) {
        formatEmailBtn.addEventListener('click', () => switchFormat('email'));
    }

    if (formatStatementBtn) {
        formatStatementBtn.addEventListener('click', () => switchFormat('statement'));
    }

    if (copyBtn) {
        copyBtn.addEventListener('click', handleCopyToClipboard);
    }

    if (gmailBtn) {
        gmailBtn.addEventListener('click', handleOpenInGmail);
    }

    if (googleDocsBtn) {
        googleDocsBtn.addEventListener('click', handleOpenInGoogleDocs);
    }

    if (downloadTxtBtn) {
        downloadTxtBtn.addEventListener('click', handleDownloadTxt);
    }

    const saveVersionBtn = document.getElementById('save-version-btn');
    if (saveVersionBtn) {
        saveVersionBtn.addEventListener('click', handleSaveVersion);
    }

    // Check if we have a profile from the profile creation event
    window.addEventListener('profile-created', (event: any) => {
        currentProfileId = event.detail.profileId;
        const generateBtn = document.getElementById('generate-draft-btn') as HTMLButtonElement;
        if (generateBtn && currentPIResearch) {
            generateBtn.disabled = false;
        }
    });

    // Add collapsible section listeners
    setupCollapsibleSections();

    if (refreshSummaryBtn) {
        refreshSummaryBtn.addEventListener('click', async () => {
            if (!currentPIResearch) {
                alert('Please gather PI research first');
                return;
            }

            // Re-gather research with new focus
            const nameInput = document.getElementById('pi-name') as HTMLInputElement;
            const orcidInput = document.getElementById('pi-orcid') as HTMLInputElement;
            const openalexInput = document.getElementById('pi-openalex-id') as HTMLInputElement;
            const institutionInput = document.getElementById('pi-institution') as HTMLInputElement;
            const summaryFocusSelect = document.getElementById('summary-focus-select') as HTMLSelectElement;

            if (!nameInput) return;

            const piName = nameInput.value.trim();
            if (!piName) {
                alert('Please enter a PI name');
                return;
            }

            const summaryFocus = summaryFocusSelect?.value || undefined;

            // Show loading
            if (refreshSummaryBtn) {
                (refreshSummaryBtn as HTMLButtonElement).disabled = true;
                (refreshSummaryBtn as HTMLButtonElement).textContent = 'Refreshing...';
            }

            try {
                const requestBody: any = {
                    pi_name: piName || undefined,
                    orcid: orcidInput?.value.trim() || undefined,
                    openalex_id: openalexInput?.value.trim() || undefined,
                    institution: institutionInput?.value.trim() || undefined,
                    summary_focus: summaryFocus,
                };

                // Remove undefined values
                Object.keys(requestBody).forEach(key => {
                    if (requestBody[key] === undefined) {
                        delete requestBody[key];
                    }
                });

                const response = await fetch('/api/v1/pi-research/gather', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(requestBody),
                });

                if (!response.ok) {
                    const error = await response.json();
                    throw new Error(error.detail || 'Failed to refresh summary');
                }

                const data: any = await response.json();

                // Update only the summary, keep the rest of the data
                if (data.pi_info && data.pi_info.summary) {
                    const summaryContent = document.getElementById('pi-summary-content');
                    if (summaryContent) {
                        const piInfoHTML = summaryContent.querySelector('.pi-info');
                        if (piInfoHTML) {
                            const summaryP = piInfoHTML.querySelector('p:last-child');
                            if (summaryP) {
                                summaryP.textContent = data.pi_info.summary;
                            }
                        }
                    }

                    // Update currentPIResearch
                    if (currentPIResearch) {
                        currentPIResearch.pi_info.summary = data.pi_info.summary;
                    }
                }
            } catch (error: any) {
                console.error('Error refreshing summary:', error);
                alert(`Error: ${error.message}`);
            } finally {
                if (refreshSummaryBtn) {
                    (refreshSummaryBtn as HTMLButtonElement).disabled = false;
                    (refreshSummaryBtn as HTMLButtonElement).textContent = 'Refresh';
                }
            }
        });
    }
}

function saveCurrentVersion(isGenerated: boolean = false): string {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const format = isEmail ? 'email' : 'statement';

    let content = '';
    let subject = '';

    if (editor && $(editor).hasClass('summernote-initialized')) {
        content = $(editor).summernote('code') || '';
    } else if (editor) {
        content = (editor as HTMLTextAreaElement).value || '';
    }

    if (isEmail) {
        const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
        subject = subjectInput?.value || '';
    }

    // Calculate word count
    const text = $('<div>').html(content).text();
    const wordCount = text.trim().split(/\s+/).filter((word: string) => word.length > 0).length;

    const version: DraftVersion = {
        id: `v${Date.now()}`,
        timestamp: new Date(),
        format,
        content,
        subject: isEmail ? subject : undefined,
        isGenerated,
        wordCount
    };

    draftVersions.push(version);
    currentVersionId = version.id;

    // Limit to 20 versions
    if (draftVersions.length > 20) {
        draftVersions.shift();
    }

    renderVersionTimeline();
    return version.id;
}

function restoreVersion(versionId: string): void {
    const version = draftVersions.find(v => v.id === versionId);
    if (!version) return;

    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const emailBtn = document.getElementById('format-email');
    const statementBtn = document.getElementById('format-statement');
    const emailOptions = document.getElementById('email-options');
    const statementOptions = document.getElementById('statement-options');

    // Switch format if needed (without saving current content)
    if (version.format === 'email') {
        emailBtn?.classList.add('active');
        statementBtn?.classList.remove('active');
        emailOptions?.setAttribute('style', 'display: block;');
        statementOptions?.setAttribute('style', 'display: none;');

        // Update email content
        emailContent.body = version.content || '';
        emailContent.subject = version.subject || '';
    } else {
        emailBtn?.classList.remove('active');
        statementBtn?.classList.add('active');
        emailOptions?.setAttribute('style', 'display: none;');
        statementOptions?.setAttribute('style', 'display: block;');

        // Update statement content
        statementContent = version.content || '';
    }

    // Set content in editor
    if (editor && $(editor).hasClass('summernote-initialized')) {
        $(editor).summernote('code', version.content || '');
    } else if (editor) {
        (editor as HTMLTextAreaElement).value = version.content || '';
    }

    // Set subject if email
    if (version.format === 'email' && version.subject !== undefined) {
        const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
        if (subjectInput) {
            subjectInput.value = version.subject;
        }
    }

    currentVersionId = versionId;
    renderVersionTimeline();
    updateWordCount();
}

function renderVersionTimeline(): void {
    const timeline = document.getElementById('version-timeline');
    if (!timeline) return;

    if (draftVersions.length === 0) {
        timeline.innerHTML = `
            <div style="text-align: center; color: #666; padding: 1rem; font-style: italic;">
                No versions yet. Start writing to see your history.
            </div>
        `;
        return;
    }

    // Sort versions by timestamp (newest first)
    const sortedVersions = [...draftVersions].sort((a, b) =>
        b.timestamp.getTime() - a.timestamp.getTime()
    );

    timeline.innerHTML = sortedVersions.map(version => {
        const isCurrent = version.id === currentVersionId;
        const timeStr = version.timestamp.toLocaleTimeString('en-US', {
            hour: 'numeric',
            minute: '2-digit',
            hour12: true
        });

        // Get preview text
        const $ = (window as any).jQuery;
        const previewText = $('<div>').html(version.content).text().trim();
        const preview = previewText.substring(0, 50) + (previewText.length > 50 ? '...' : '');

        const versionName = version.isGenerated
            ? `v${sortedVersions.length - sortedVersions.indexOf(version)} (Generated)`
            : version.id === sortedVersions[sortedVersions.length - 1].id
                ? 'Initial Draft'
                : `v${sortedVersions.length - sortedVersions.indexOf(version)}`;

        return `
            <div class="version-card" data-version-id="${version.id}"
                 style="padding: 0.75rem; margin-bottom: 0.5rem; border: 2px solid ${isCurrent ? '#007bff' : '#dee2e6'};
                        border-radius: 6px; background-color: ${isCurrent ? '#e7f3ff' : '#ffffff'};
                        cursor: pointer; transition: all 0.2s;"
                 onmouseover="this.style.backgroundColor='${isCurrent ? '#d0e7ff' : '#f8f9fa'}'"
                 onmouseout="this.style.backgroundColor='${isCurrent ? '#e7f3ff' : '#ffffff'}'">
                <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 0.25rem;">
                    <div style="font-weight: ${isCurrent ? 'bold' : '600'}; font-size: 0.9em; color: ${isCurrent ? '#007bff' : '#333'};">
                        ${versionName} ${isCurrent ? '← Current' : ''}
                    </div>
                    <div style="font-size: 0.75em; color: #666;">${timeStr}</div>
                </div>
                <div style="font-size: 0.8em; color: #666; margin-bottom: 0.25rem;">
                    ${version.format === 'email' ? '📧 Email' : '📝 Statement'}
                    ${version.wordCount ? ` • ${version.wordCount} words` : ''}
                </div>
                <div style="font-size: 0.75em; color: #888; font-style: italic;">
                    ${preview || '(empty)'}
                </div>
            </div>
        `;
    }).join('');

    // Add click handlers
    timeline.querySelectorAll('.version-card').forEach(card => {
        card.addEventListener('click', () => {
            const versionId = card.getAttribute('data-version-id');
            if (versionId) {
                restoreVersion(versionId);
            }
        });
    });
}

function handleSaveVersion(): void {
    saveCurrentVersion(false);
    // Show brief feedback
    const btn = document.getElementById('save-version-btn') as HTMLButtonElement;
    if (btn) {
        const originalText = btn.textContent;
        btn.textContent = 'Saved!';
        setTimeout(() => {
            btn.textContent = originalText;
        }, 1000);
    }
}

function switchFormat(format: 'email' | 'statement'): void {
    // Save current content before switching
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const formatEmailBtn = document.getElementById('format-email');
    const currentFormat = formatEmailBtn?.classList.contains('active') ? 'email' : 'statement';

    if (currentFormat !== format) {
        // Save current format's content
        if (currentFormat === 'email') {
            if (editor && $(editor).hasClass('summernote-initialized')) {
                emailContent.body = $(editor).summernote('code') || '';
            } else if (editor) {
                emailContent.body = (editor as HTMLTextAreaElement).value || '';
            }
            const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
            if (subjectInput) {
                emailContent.subject = subjectInput.value || '';
            }
        } else {
            if (editor && $(editor).hasClass('summernote-initialized')) {
                statementContent = $(editor).summernote('code') || '';
            } else if (editor) {
                statementContent = (editor as HTMLTextAreaElement).value || '';
            }
        }
    }

    const emailBtn = document.getElementById('format-email');
    const statementBtn = document.getElementById('format-statement');
    const emailOptions = document.getElementById('email-options');
    const statementOptions = document.getElementById('statement-options');
    const editorEl = document.getElementById('draft-editor');

    if (format === 'email') {
        emailBtn?.classList.add('active');
        statementBtn?.classList.remove('active');
        emailOptions?.setAttribute('style', 'display: block;');
        statementOptions?.setAttribute('style', 'display: none;');

        // Load email content
        if (editorEl && $(editorEl).hasClass('summernote-initialized')) {
            $(editorEl).summernote('code', emailContent.body);
        } else if (editorEl) {
            (editorEl as HTMLTextAreaElement).value = emailContent.body;
        }
        const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
        if (subjectInput) {
            subjectInput.value = emailContent.subject;
        }
    } else {
        emailBtn?.classList.remove('active');
        statementBtn?.classList.add('active');
        emailOptions?.setAttribute('style', 'display: none;');
        statementOptions?.setAttribute('style', 'display: block;');

        // Load statement content
        if (editorEl && $(editorEl).hasClass('summernote-initialized')) {
            $(editorEl).summernote('code', statementContent);
        } else if (editorEl) {
            (editorEl as HTMLTextAreaElement).value = statementContent;
        }
    }

    updateWordCount();
}

function displayPIResearch(data: PIResearchData): void {
    const summarySection = document.getElementById('pi-summary-section');
    const clinicalTrialsSection = document.getElementById('clinical-trials-section');
    const papersSection = document.getElementById('papers-section');

    // Display PI summary
    if (summarySection) {
        const summaryContent = document.getElementById('pi-summary-content');
        if (summaryContent) {
            // Get institutions - try last_known_institutions first, then affiliated_institutions, then institution
            let institutions: string[] = [];
            if (data.pi_info.last_known_institutions && Array.isArray(data.pi_info.last_known_institutions)) {
                institutions = data.pi_info.last_known_institutions.map((inst: any) =>
                    typeof inst === 'string' ? inst : (inst.display_name || inst.name || '')
                ).filter((inst: string) => inst);
            } else if (data.pi_info.affiliated_institutions && Array.isArray(data.pi_info.affiliated_institutions)) {
                institutions = data.pi_info.affiliated_institutions;
            } else if (data.pi_info.institution) {
                institutions = [data.pi_info.institution];
            }

            summaryContent.innerHTML = `
                <div class="pi-info">
                    <h4>${data.pi_info.name}</h4>
                    ${institutions.length > 0 ? `<p><strong>Institution${institutions.length > 1 ? 's' : ''}:</strong> ${institutions.join(', ')}</p>` : ''}
                    ${data.pi_info.summary ? `<p>${data.pi_info.summary}</p>` : ''}
                </div>
            `;
            summarySection.style.display = 'block';
        }
    }

    // Display clinical trials
    if (clinicalTrialsSection && data.clinical_trials && data.clinical_trials.length > 0) {
        const clinicalTrialsList = document.getElementById('clinical-trials-list');
        if (clinicalTrialsList) {
            // Reset collapse state and ensure section is expanded
            clinicalTrialsCollapsed = false;
            clinicalTrialsList.style.display = 'block';
            const chevron = document.getElementById('clinical-trials-chevron');
            if (chevron) chevron.textContent = '▼';

            // Reset selection when new data is loaded
            selectedTrials.clear();
            clinicalTrialsList.innerHTML = data.clinical_trials.map((trial, idx) => {
                const nctId = trial.nct_id || 'N/A';
                const phase = trial.phase ? ` | Phase: ${trial.phase}` : '';
                const status = trial.overall_status || 'Unknown';
                const statusColor = status.includes('RECRUITING') ? '#28a745' : status.includes('ACTIVE') ? '#007bff' : '#6c757d';
                const alignmentScore = trial.alignment_score !== undefined ? ` (Alignment: ${(trial.alignment_score * 100).toFixed(0)}%)` : '';
                const conditions = trial.conditions && trial.conditions.length > 0 ? trial.conditions.join(', ') : 'N/A';
                const piName = trial.pi_name || 'N/A';
                const isChecked = selectedTrials.has(idx) ? 'checked' : '';

                return `
                    <div class="clinical-trial-item" style="background-color: white; border: 1px solid #dee2e6; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; display: flex; gap: 0.75rem;">
                        <input type="checkbox" class="trial-checkbox" data-trial-idx="${idx}" ${isChecked}
                            style="margin-top: 0.25rem; cursor: pointer;">
                        <div style="flex: 1;">
                            <h5 style="margin-top: 0; margin-bottom: 0.5rem;">${trial.title || 'Untitled Trial'}</h5>
                            <div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;">
                                <strong>Principal Investigator:</strong> ${piName}
                            </div>
                            <div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;">
                                <strong>NCT ID:</strong> ${nctId}${phase}${alignmentScore}
                            </div>
                            <div style="font-size: 0.9em; margin-bottom: 0.5rem;">
                                <strong>Status:</strong> <span style="color: ${statusColor}; font-weight: bold;">${status}</span>
                            </div>
                            <div style="font-size: 0.9em; margin-bottom: 0.5rem;">
                                <strong>Conditions:</strong> ${conditions}
                            </div>
                            ${trial.brief_summary ? `<p style="font-size: 0.9em; margin-bottom: 0.5rem;">${trial.brief_summary.substring(0, 200)}${trial.brief_summary.length > 200 ? '...' : ''}</p>` : ''}
                            ${trial.key_themes && trial.key_themes.length > 0 ? `<p style="font-size: 0.85em; color: #666;"><strong>Themes:</strong> ${trial.key_themes.join(', ')}</p>` : ''}
                            ${trial.nct_id ? `<a href="https://clinicaltrials.gov/study/${trial.nct_id}" target="_blank" rel="noopener" style="font-size: 0.9em;">View on ClinicalTrials.gov</a>` : ''}
                        </div>
                    </div>
                `;
            }).join('');
            clinicalTrialsSection.style.display = 'block';

            // Re-attach collapsible listener
            const clinicalTrialsHeader = document.getElementById('clinical-trials-header');
            if (clinicalTrialsHeader) {
                // Remove old listeners and add new one
                const newHeader = clinicalTrialsHeader.cloneNode(true);
                clinicalTrialsHeader.parentNode?.replaceChild(newHeader, clinicalTrialsHeader);
                (newHeader as HTMLElement).addEventListener('click', () => toggleSection('clinical-trials'));
            }

            // Attach checkbox listeners
            clinicalTrialsList.querySelectorAll('.trial-checkbox').forEach(checkbox => {
                checkbox.addEventListener('change', (e) => {
                    const idx = parseInt((e.target as HTMLElement).getAttribute('data-trial-idx') || '-1');
                    if (idx >= 0) {
                        if ((e.target as HTMLInputElement).checked) {
                            selectedTrials.add(idx);
                        } else {
                            selectedTrials.delete(idx);
                        }
                    }
                });
            });
        }
    } else if (clinicalTrialsSection) {
        clinicalTrialsSection.style.display = 'none';
    }

    // Display NIH projects
    const nihProjectsSection = document.getElementById('nih-projects-section');
    if (nihProjectsSection && data.nih_projects && data.nih_projects.length > 0) {
        const nihProjectsList = document.getElementById('nih-projects-list');
        if (nihProjectsList) {
            // Reset collapse state and ensure section is expanded
            nihProjectsCollapsed = false;
            nihProjectsList.style.display = 'block';
            const chevron = document.getElementById('nih-projects-chevron');
            if (chevron) chevron.textContent = '▼';

            // Reset selection when new data is loaded
            selectedNihProjects.clear();
            nihProjectsList.innerHTML = data.nih_projects.map((project, idx) => {
                const title = project.project_title || 'Untitled Project';
                const fiscalYear = project.fiscal_year ? `FY ${project.fiscal_year}` : '';
                const awardAmount = project.award_amount ? `$${project.award_amount.toLocaleString()}` : 'N/A';
                const organization = project.organization || 'N/A';
                const phrText = project.phr_text || '';
                const projectStartDate = project.project_start_date || '';
                const projectEndDate = project.project_end_date || '';
                const activityCode = project.activity_code || '';
                const isChecked = selectedNihProjects.has(idx) ? 'checked' : '';

                return `
                    <div class="nih-project-item" style="background-color: white; border: 1px solid #dee2e6; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; display: flex; gap: 0.75rem;">
                        <input type="checkbox" class="nih-project-checkbox" data-project-idx="${idx}" ${isChecked}
                            style="margin-top: 0.25rem; cursor: pointer;">
                        <div style="flex: 1;">
                            <h5 style="margin-top: 0; margin-bottom: 0.5rem;">${title}</h5>
                            <div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;">
                                <strong>Fiscal Year:</strong> ${fiscalYear} | <strong>Award Amount:</strong> ${awardAmount}
                            </div>
                            <div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;">
                                <strong>Organization:</strong> ${organization}
                            </div>
                            ${activityCode ? `<div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;"><strong>Activity Code:</strong> ${activityCode}</div>` : ''}
                            ${projectStartDate || projectEndDate ? `<div style="font-size: 0.9em; color: #666; margin-bottom: 0.5rem;"><strong>Project Dates:</strong> ${projectStartDate || 'N/A'} - ${projectEndDate || 'Ongoing'}</div>` : ''}
                            ${phrText ? `<div style="font-size: 0.9em; margin-bottom: 0.5rem;"><strong>Summary:</strong> <span style="color: #333;">${phrText.substring(0, 300)}${phrText.length > 300 ? '...' : ''}</span></div>` : ''}
                            ${project.core_project_num ? `<div style="font-size: 0.9em; color: #666;"><strong>Project Number:</strong> <a href="${project.search_url || `https://reporter.nih.gov/search/${project.core_project_num}`}" target="_blank" rel="noopener" style="color: #007bff; text-decoration: underline;">${project.core_project_num}</a></div>` : ''}
                        </div>
                    </div>
                `;
            }).join('');
            nihProjectsSection.style.display = 'block';

            // Re-attach collapsible listener
            const nihProjectsHeader = document.getElementById('nih-projects-header');
            if (nihProjectsHeader) {
                // Remove old listeners and add new one
                const newHeader = nihProjectsHeader.cloneNode(true);
                nihProjectsHeader.parentNode?.replaceChild(newHeader, nihProjectsHeader);
                (newHeader as HTMLElement).addEventListener('click', () => toggleSection('nih-projects'));
            }

            // Attach checkbox listeners
            nihProjectsList.querySelectorAll('.nih-project-checkbox').forEach(checkbox => {
                checkbox.addEventListener('change', (e) => {
                    const idx = parseInt((e.target as HTMLElement).getAttribute('data-project-idx') || '-1');
                    if (idx >= 0) {
                        if ((e.target as HTMLInputElement).checked) {
                            selectedNihProjects.add(idx);
                        } else {
                            selectedNihProjects.delete(idx);
                        }
                    }
                });
            });
        }
    } else if (nihProjectsSection) {
        nihProjectsSection.style.display = 'none';
    }

    // Display papers with pagination
    if (papersSection && data.papers.length > 0) {
        // Reset collapse state and ensure section is expanded
        papersCollapsed = false;
        const papersList = document.getElementById('papers-list');
        if (papersList) papersList.style.display = 'block';
        const chevron = document.getElementById('papers-chevron');
        if (chevron) chevron.textContent = '▼';

        currentPapersPage = 1; // Reset to first page when new data is loaded
        selectedPapers.clear(); // Reset selection when new data is loaded
        renderPapersList(data.papers);
        papersSection.style.display = 'block';

        // Re-attach collapsible listener
        const papersHeader = document.getElementById('papers-header');
        if (papersHeader) {
            // Remove old listeners and add new one
            const newHeader = papersHeader.cloneNode(true);
            papersHeader.parentNode?.replaceChild(newHeader, papersHeader);
            (newHeader as HTMLElement).addEventListener('click', () => toggleSection('papers'));
        }
    } else if (papersSection) {
        papersSection.style.display = 'none';
    }

    // Add Regenerate Summary button if we have research data
    if (summarySection && (data.papers.length > 0 || (data.clinical_trials && data.clinical_trials.length > 0) || (data.nih_projects && data.nih_projects.length > 0))) {
        const summaryContent = document.getElementById('pi-summary-content');
        if (summaryContent) {
            const existingContent = summaryContent.innerHTML;
            // Only add button if it doesn't already exist
            if (!existingContent.includes('regenerate-summary-btn')) {
                summaryContent.innerHTML += `
                    <div style="margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #dee2e6;">
                        <button id="regenerate-summary-btn" class="btn-secondary"
                            style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">
                            Regenerate Summary
                        </button>
                        <p style="font-size: 0.85em; color: #666; margin-top: 0.5rem;">
                            Select papers, projects, or trials above to regenerate the summary with only selected items.
                        </p>
                    </div>
                `;

                // Attach regenerate button listener
                const regenerateBtn = document.getElementById('regenerate-summary-btn');
                if (regenerateBtn) {
                    regenerateBtn.addEventListener('click', () => handleRegenerateSummary(data));
                }
            }
        }
    }

    // Enable generate button if we have a profile
    const generateBtn = document.getElementById('generate-draft-btn') as HTMLButtonElement;
    if (generateBtn && currentProfileId) {
        generateBtn.disabled = false;
    } else if (generateBtn) {
        generateBtn.disabled = true;
        generateBtn.title = 'Please create a profile first';
    }
}

async function handleGatherResearch(): Promise<void> {
    const nameInput = document.getElementById('pi-name') as HTMLInputElement;
    const orcidInput = document.getElementById('pi-orcid') as HTMLInputElement;
    const openalexInput = document.getElementById('pi-openalex-id') as HTMLInputElement;
    const institutionInput = document.getElementById('pi-institution') as HTMLInputElement;
    const gatherBtn = document.getElementById('gather-research-btn') as HTMLButtonElement;
    const summarySection = document.getElementById('pi-summary-section');
    const papersSection = document.getElementById('papers-section');

    if (!nameInput || !gatherBtn) return;

    const piName = nameInput.value.trim();
    if (!piName) {
        alert('Please enter a PI name');
        return;
    }

    // Show loading state
    gatherBtn.disabled = true;
    gatherBtn.textContent = 'Gathering Research...';

    try {
        const summaryFocusSelect = document.getElementById('summary-focus-select') as HTMLSelectElement;
        const summaryFocus = summaryFocusSelect?.value || undefined;

        const requestBody: any = {
            pi_name: piName || undefined,
            orcid: orcidInput?.value.trim() || undefined,
            openalex_id: openalexInput?.value.trim() || undefined,
            institution: institutionInput?.value.trim() || undefined,
            summary_focus: summaryFocus,
        };

        // Remove undefined values
        Object.keys(requestBody).forEach(key => {
            if (requestBody[key] === undefined) {
                delete requestBody[key];
            }
        });

        const response = await fetch('/api/v1/pi-research/gather', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(requestBody),
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.detail || 'Failed to gather PI research');
        }

        const data: any = await response.json();

        // Check if multiple matches were returned
        if (data.multiple_matches && data.candidates) {
            // Show candidate selection UI
            if (summarySection) {
                const summaryContent = document.getElementById('pi-summary-content');
                if (summaryContent) {
                    summaryContent.innerHTML = `
                        <div class="pi-info">
                            <h4>Multiple Researchers Found</h4>
                            <p>Please select the correct researcher:</p>
                            <div id="pi-candidates-list" style="margin-top: 1rem;">
                                ${data.candidates.map((candidate: any, idx: number) => {
                                    // Get institutions - try last_known_institutions first, then affiliated_institutions, then institution
                                    let institutions: string[] = [];
                                    if (candidate.last_known_institutions && Array.isArray(candidate.last_known_institutions)) {
                                        institutions = candidate.last_known_institutions.map((inst: any) =>
                                            typeof inst === 'string' ? inst : (inst.display_name || inst.name || '')
                                        ).filter((inst: string) => inst);
                                    } else if (candidate.affiliated_institutions && Array.isArray(candidate.affiliated_institutions)) {
                                        institutions = candidate.affiliated_institutions;
                                    } else if (candidate.institution) {
                                        institutions = [candidate.institution];
                                    }
                                    return `
                                    <div class="candidate-select-card" style="background-color: white; border: 2px solid #dee2e6; border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; cursor: pointer; transition: border-color 0.2s;"
                                         data-openalex-id="${candidate.openalex_id}">
                                        <div>
                                            <h5 style="margin: 0 0 0.5rem 0;">${candidate.name}</h5>
                                            ${institutions.length > 0 ? `<p style="margin: 0 0 0.5rem 0; color: #666; font-size: 0.9em;"><strong>Institutions:</strong> ${institutions.join(', ')}</p>` : ''}
                                            ${candidate.subjects && candidate.subjects.length > 0 ? `<p style="margin: 0 0 0.5rem 0; color: #666; font-size: 0.9em;"><strong>Subjects:</strong> ${candidate.subjects.join(', ')}</p>` : ''}
                                            <div style="font-size: 0.9em; color: #666;">
                                                <strong>h-index:</strong> ${candidate.h_index || 0}
                                            </div>
                                        </div>
                                    </div>
                                `;
                                }).join('')}
                            </div>
                        </div>
                    `;
                    summarySection.style.display = 'block';

                    // Add click handlers for candidate selection
                    document.querySelectorAll('.candidate-select-card').forEach(card => {
                        card.addEventListener('click', async () => {
                            const openalexId = (card as HTMLElement).dataset.openalexId;
                            if (openalexId) {
                                // Gather research for selected candidate
                                gatherBtn.disabled = true;
                                gatherBtn.textContent = 'Gathering Research...';

                                try {
                                    const selectResponse = await fetch('/api/v1/pi-research/gather', {
                                        method: 'POST',
                                        headers: { 'Content-Type': 'application/json' },
                                        body: JSON.stringify({ openalex_id: openalexId }),
                                    });

                                    if (!selectResponse.ok) {
                                        const error = await selectResponse.json();
                                        throw new Error(error.detail || 'Failed to gather PI research');
                                    }

                                    const selectedData: PIResearchData = await selectResponse.json();
                                    currentPIResearch = selectedData;

                                    // Display selected PI summary
                                    displayPIResearch(selectedData);

                                } catch (error: any) {
                                    console.error('Error gathering research:', error);
                                    alert(`Error: ${error.message}`);
                                } finally {
                                    gatherBtn.disabled = false;
                                    gatherBtn.textContent = 'Gather Research';
                                }
                            }
                        });

                        // Add hover effect
                        card.addEventListener('mouseenter', () => {
                            (card as HTMLElement).style.borderColor = '#007bff';
                        });
                        card.addEventListener('mouseleave', () => {
                            (card as HTMLElement).style.borderColor = '#dee2e6';
                        });
                    });
                }
            }
            return;
        }

        // Single match - proceed normally
        const piData: PIResearchData = data;
        currentPIResearch = piData;

        // Display PI summary
        displayPIResearch(piData);

        // Enable generate button if we have a profile
        const generateBtn = document.getElementById('generate-draft-btn') as HTMLButtonElement;
        if (generateBtn && currentProfileId) {
            generateBtn.disabled = false;
        } else if (generateBtn) {
            generateBtn.disabled = true;
            generateBtn.title = 'Please create a profile first';
        }

    } catch (error: any) {
        console.error('Error gathering research:', error);
        alert(`Error: ${error.message}`);
    } finally {
        gatherBtn.disabled = false;
        gatherBtn.textContent = 'Gather Research';
    }
}

async function handleGenerateDraft(): Promise<void> {
    if (!currentProfileId) {
        alert('Please create a profile first');
        return;
    }

    if (!currentPIResearch) {
        alert('Please gather PI research first');
        return;
    }

    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const formatType = isEmail ? 'email' : 'statement';

    const generateBtn = document.getElementById('generate-draft-btn') as HTMLButtonElement;
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');

    if (!generateBtn || !editor) return;

    // Save current editor content as a version before generating (if not empty)
    const currentContent = $(editor).hasClass('summernote-initialized')
        ? $(editor).summernote('code') || ''
        : (editor as HTMLTextAreaElement).value || '';

    if (currentContent.trim()) {
        saveCurrentVersion(false);
    }

    // Show loading
    generateBtn.disabled = true;
    generateBtn.textContent = 'Generating...';

    try {
        const requestBody: any = {
            profile_id: currentProfileId,
            pi_research_data: currentPIResearch,
            format_type: formatType,
        };

        // Get user draft from editor
        const userDraft = currentContent.trim();
        if (formatType === 'email') {
            const wordCount = parseInt((document.getElementById('email-word-count-target') as HTMLInputElement)?.value || '300');
            if (userDraft) {
                requestBody.user_draft = userDraft;
            }
            requestBody.word_count_target = wordCount;
        } else {
            const wordCount = parseInt((document.getElementById('statement-word-count-target') as HTMLInputElement)?.value || '375');
            if (userDraft) {
                requestBody.user_draft = userDraft;
            }
            requestBody.word_count_target = wordCount;
        }

        const response = await fetch('/api/v1/draft/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(requestBody),
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.detail || 'Failed to generate draft');
        }

        const result = await response.json();

        // Repopulate editor with generated content
        if (formatType === 'email') {
            const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
            if (subjectInput) {
                subjectInput.value = result.subject || '';
                emailContent.subject = result.subject || '';
            }

            // Set body in editor
            if ($(editor).hasClass('summernote-initialized')) {
                $(editor).summernote('code', result.body || '');
            } else {
                (editor as HTMLTextAreaElement).value = result.body || '';
            }
            emailContent.body = result.body || '';
        } else {
            // Set statement in editor
            if ($(editor).hasClass('summernote-initialized')) {
                $(editor).summernote('code', result.statement || '');
            } else {
                (editor as HTMLTextAreaElement).value = result.statement || '';
            }
            statementContent = result.statement || '';
        }

        // Save generated content as a new version
        saveCurrentVersion(true);
        updateWordCount();

    } catch (error: any) {
        console.error('Error generating draft:', error);
        alert(`Error: ${error.message}`);
    } finally {
        generateBtn.disabled = false;
        generateBtn.textContent = 'Generate Draft';
    }
}

async function handleEnhanceDraft(): Promise<void> {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const formatType = isEmail ? 'email' : 'statement';
    const enhanceBtn = document.getElementById('enhance-draft-btn') as HTMLButtonElement;

    if (!editor || !enhanceBtn) return;

    // Get current draft content
    let currentDraft = '';
    if ($(editor).hasClass('summernote-initialized')) {
        currentDraft = $(editor).summernote('code') || '';
    } else {
        currentDraft = (editor as HTMLTextAreaElement).value || '';
    }

    // Convert HTML to plain text for analysis
    const $temp = $('<div>').html(currentDraft);
    const plainText = $temp.text().trim();

    if (!plainText) {
        alert('Please write some content first before enhancing');
        return;
    }

    // Show loading
    enhanceBtn.disabled = true;
    enhanceBtn.textContent = 'Enhancing...';

    try {
        const requestBody: any = {
            current_draft: plainText,
            format_type: formatType,
        };

        // Add optional context if available
        if (currentProfileId) {
            requestBody.profile_id = currentProfileId;
        }

        if (currentPIResearch) {
            requestBody.pi_research_data = currentPIResearch;
        }

        const response = await fetch('/api/v1/draft/enhance', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(requestBody),
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.detail || 'Failed to enhance draft');
        }

        const result = await response.json();

        // Show enhancement results in a modal or side-by-side view
        showEnhancementResults(result, currentDraft, formatType);

    } catch (error: any) {
        console.error('Error enhancing draft:', error);
        alert(`Error: ${error.message}`);
    } finally {
        enhanceBtn.disabled = false;
        enhanceBtn.textContent = 'Enhance Draft';
    }
}

function showEnhancementResults(result: any, originalDraft: string, formatType: string): void {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');

    // Create modal or side-by-side view
    const modal = document.createElement('div');
    modal.style.cssText = `
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.7);
        z-index: 10000;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 2rem;
    `;

    const qualityScore = result.quality_score || 0;
    const qualityColor = qualityScore >= 0.7 ? '#28a745' : qualityScore >= 0.5 ? '#ffc107' : '#dc3545';

    modal.innerHTML = `
        <div style="background-color: white; border-radius: 8px; padding: 2rem; max-width: 1200px; max-height: 90vh; overflow-y: auto; width: 100%;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
                <h2 style="margin: 0;">Draft Enhancement Results</h2>
                <button id="close-enhancement-modal" style="background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #666;">&times;</button>
            </div>

            <div style="margin-bottom: 1.5rem;">
                <div style="display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem;">
                    <span style="font-weight: bold;">Quality Score:</span>
                    <div style="flex: 1; background-color: #e9ecef; border-radius: 4px; height: 24px; position: relative;">
                        <div style="background-color: ${qualityColor}; height: 100%; width: ${qualityScore * 100}%; border-radius: 4px; transition: width 0.3s;"></div>
                        <span style="position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%); font-size: 0.9em; font-weight: bold; color: ${qualityScore >= 0.5 ? 'white' : '#333'};">
                            ${(qualityScore * 100).toFixed(0)}%
                        </span>
                    </div>
                </div>

                <div style="background-color: #f8f9fa; border-left: 4px solid #007bff; padding: 1rem; margin-bottom: 1rem;">
                    <h4 style="margin-top: 0;">Feedback</h4>
                    ${result.feedback.weaknesses && result.feedback.weaknesses.length > 0 ? `
                        <div style="margin-bottom: 0.75rem;">
                            <strong>Weaknesses:</strong>
                            <ul style="margin: 0.5rem 0 0 1.5rem;">
                                ${result.feedback.weaknesses.map((w: string) => `<li>${w}</li>`).join('')}
                            </ul>
                        </div>
                    ` : ''}
                    ${result.feedback.missing_elements && result.feedback.missing_elements.length > 0 ? `
                        <div style="margin-bottom: 0.75rem;">
                            <strong>Missing Elements:</strong>
                            <ul style="margin: 0.5rem 0 0 1.5rem;">
                                ${result.feedback.missing_elements.map((e: string) => `<li>${e}</li>`).join('')}
                            </ul>
                        </div>
                    ` : ''}
                    ${result.feedback.specific_suggestions && result.feedback.specific_suggestions.length > 0 ? `
                        <div>
                            <strong>Suggestions:</strong>
                            <ul style="margin: 0.5rem 0 0 1.5rem;">
                                ${result.feedback.specific_suggestions.map((s: string) => `<li>${s}</li>`).join('')}
                            </ul>
                        </div>
                    ` : ''}
                </div>
            </div>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1.5rem;">
                <div>
                    <h4 style="margin-top: 0;">Original Draft</h4>
                    <div style="background-color: #f8f9fa; border: 1px solid #dee2e6; border-radius: 4px; padding: 1rem; max-height: 400px; overflow-y: auto; white-space: pre-wrap; font-size: 0.9em;">
                        ${originalDraft || '(empty)'}
                    </div>
                </div>
                <div>
                    <h4 style="margin-top: 0;">Enhanced Draft</h4>
                    <div style="background-color: #e7f3ff; border: 1px solid #007bff; border-radius: 4px; padding: 1rem; max-height: 400px; overflow-y: auto; white-space: pre-wrap; font-size: 0.9em;">
                        ${result.enhanced_draft || '(no enhancement generated)'}
                    </div>
                </div>
            </div>

            <div style="display: flex; gap: 0.5rem; justify-content: flex-end;">
                <button id="reject-enhancement" style="padding: 0.5rem 1rem; background-color: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Cancel</button>
                <button id="accept-enhancement" style="padding: 0.5rem 1rem; background-color: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer;">Use Enhanced Version</button>
            </div>
        </div>
    `;

    document.body.appendChild(modal);

    // Close button
    const closeBtn = document.getElementById('close-enhancement-modal');
    const rejectBtn = document.getElementById('reject-enhancement');
    const acceptBtn = document.getElementById('accept-enhancement');

    const closeModal = () => {
        document.body.removeChild(modal);
    };

    if (closeBtn) {
        closeBtn.addEventListener('click', closeModal);
    }

    if (rejectBtn) {
        rejectBtn.addEventListener('click', closeModal);
    }

    if (acceptBtn) {
        acceptBtn.addEventListener('click', () => {
            // Replace editor content with enhanced draft
            if (editor && $(editor).hasClass('summernote-initialized')) {
                $(editor).summernote('code', result.enhanced_draft);
            } else if (editor) {
                (editor as HTMLTextAreaElement).value = result.enhanced_draft;
            }

            // Save as a new version
            saveCurrentVersion(false);
            updateWordCount();

            closeModal();
        });
    }

    // Close on outside click
    modal.addEventListener('click', (e) => {
        if (e.target === modal) {
            closeModal();
        }
    });
}

function copyToClipboard(text: string): void {
    // Try modern Clipboard API first (requires document focus)
    if (navigator.clipboard && window.isSecureContext) {
        // Ensure window is focused
        window.focus();

        navigator.clipboard.writeText(text).then(() => {
            alert('Copied to clipboard!');
        }).catch(err => {
            console.warn('Clipboard API failed, using fallback:', err);
            // Fallback to legacy method
            copyToClipboardFallback(text);
        });
    } else {
        // Use fallback for browsers without Clipboard API
        copyToClipboardFallback(text);
    }
}

function copyToClipboardFallback(text: string): void {
    // Create a temporary textarea element
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.left = '-999999px';
    textarea.style.top = '-999999px';
    document.body.appendChild(textarea);

    // Select and copy
    textarea.focus();
    textarea.select();

    try {
        const successful = document.execCommand('copy');
        if (successful) {
            alert('Copied to clipboard!');
        } else {
            alert('Failed to copy to clipboard. Please copy manually.');
        }
    } catch (err) {
        console.error('Fallback copy failed:', err);
        alert('Failed to copy to clipboard. Please copy manually.');
    } finally {
        document.body.removeChild(textarea);
    }
}

function getEditorContent(): { content: string; subject?: string } {
    const $ = (window as any).jQuery;
    const editor = document.getElementById('draft-editor');
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');

    let content = '';
    let subject = '';

    if (editor && $(editor).hasClass('summernote-initialized')) {
        content = $(editor).summernote('code') || '';
    } else if (editor) {
        content = (editor as HTMLTextAreaElement).value || '';
    }

    if (isEmail) {
        const subjectInput = document.getElementById('email-subject') as HTMLInputElement;
        subject = subjectInput?.value || '';
    }

    return { content, subject: isEmail ? subject : undefined };
}

function handleCopyToClipboard(): void {
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const { content, subject } = getEditorContent();

    if (!content.trim()) {
        alert('No content to copy');
        return;
    }

    // Convert HTML to plain text for clipboard
    const $ = (window as any).jQuery;
    const text = $('<div>').html(content).text();

    let textToCopy = '';
    if (isEmail && subject) {
        textToCopy = `Subject: ${subject}\n\n${text}`;
    } else {
        textToCopy = text;
    }

    // Copy to clipboard with fallback
    copyToClipboard(textToCopy);
}

function handleOpenInGmail(): void {
    const { content, subject } = getEditorContent();

    if (!subject || !content.trim()) {
        alert('No email content to open');
        return;
    }

    // Convert HTML to plain text for email
    const $ = (window as any).jQuery;
    const bodyText = $('<div>').html(content).text();

    const encodedSubject = encodeURIComponent(subject);
    const encodedBody = encodeURIComponent(bodyText);
    const mailtoLink = `https://mail.google.com/mail/?view=cm&fs=1&to=&su=${encodedSubject}&body=${encodedBody}`;

    window.open(mailtoLink, '_blank');
}

async function handleOpenInGoogleDocs(): Promise<void> {
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const { content, subject } = getEditorContent();

    if (!content.trim()) {
        alert('No content to open');
        return;
    }

    // Convert HTML to plain text
    const $ = (window as any).jQuery;
    const text = $('<div>').html(content).text();

    let docContent = '';
    let title = '';
    if (isEmail && subject) {
        title = subject;
        docContent = `Subject: ${subject}\n\n${text}`;
    } else {
        title = 'Statement of Interest';
        docContent = text;
    }

    // Copy content to clipboard first (before opening new window)
    try {
        // Use modern Clipboard API with better error handling
        if (navigator.clipboard && window.isSecureContext) {
            await navigator.clipboard.writeText(docContent);
        } else {
            // Fallback for older browsers
            const textArea = document.createElement('textarea');
            textArea.value = docContent;
            textArea.style.position = 'fixed';
            textArea.style.left = '-999999px';
            textArea.style.top = '-999999px';
            document.body.appendChild(textArea);
            textArea.focus();
            textArea.select();

            try {
                const successful = document.execCommand('copy');
                if (!successful) {
                    throw new Error('execCommand copy failed');
                }
            } finally {
                document.body.removeChild(textArea);
            }
        }

        // Create a Google Docs URL
        const encodedTitle = encodeURIComponent(title);
        const docsUrl = `https://docs.google.com/document/create?title=${encodedTitle}`;

        // Open Google Docs in new tab
        window.open(docsUrl, '_blank');

        // Show clear instructions
        alert('✓ Content copied to clipboard!\n\nA new Google Doc is opening. Once it loads:\n1. Click in the document\n2. Press Ctrl+V (or Cmd+V on Mac) to paste\n\nThe content is ready in your clipboard.');

    } catch (error) {
        console.error('Error copying to clipboard:', error);
        // Still open the doc, but provide manual copy instructions
        const encodedTitle = encodeURIComponent(title);
        const docsUrl = `https://docs.google.com/document/create?title=${encodedTitle}`;
        window.open(docsUrl, '_blank');

        // Show text in a prompt for manual copying
        const userConfirmed = confirm(
            'Could not automatically copy to clipboard.\n\n' +
            'A new Google Doc is opening. Please:\n' +
            '1. Select and copy the text below\n' +
            '2. Paste it into the Google Doc\n\n' +
            'Click OK to see the text to copy.'
        );

        if (userConfirmed) {
            // Show text in a textarea for easy selection
            const textArea = document.createElement('textarea');
            textArea.value = docContent;
            textArea.style.width = '80%';
            textArea.style.height = '300px';
            textArea.style.position = 'fixed';
            textArea.style.top = '50%';
            textArea.style.left = '50%';
            textArea.style.transform = 'translate(-50%, -50%)';
            textArea.style.zIndex = '10000';
            textArea.style.padding = '10px';
            textArea.style.border = '2px solid #007bff';
            textArea.style.borderRadius = '4px';
            textArea.style.fontSize = '14px';
            document.body.appendChild(textArea);
            textArea.select();

            // Remove after 30 seconds or when user clicks outside
            setTimeout(() => {
                if (document.body.contains(textArea)) {
                    document.body.removeChild(textArea);
                }
            }, 30000);

            textArea.addEventListener('blur', () => {
                setTimeout(() => {
                    if (document.body.contains(textArea)) {
                        document.body.removeChild(textArea);
                    }
                }, 100);
            });
        }
    }
}

function handleDownloadTxt(): void {
    const formatEmailBtn = document.getElementById('format-email');
    const isEmail = formatEmailBtn?.classList.contains('active');
    const { content, subject } = getEditorContent();

    if (!content.trim()) {
        alert('No content to download');
        return;
    }

    // Convert HTML to plain text
    const $ = (window as any).jQuery;
    const text = $('<div>').html(content).text();

    let fileContent = '';
    let filename = '';
    if (isEmail && subject) {
        filename = `email_${subject.replace(/[^a-z0-9]/gi, '_') || 'draft'}.txt`;
        fileContent = `Subject: ${subject}\n\n${text}`;
    } else {
        filename = 'statement_of_interest.txt';
        fileContent = text;
    }

    const blob = new Blob([fileContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function renderPapersList(papers: Paper[]): void {
    const papersList = document.getElementById('papers-list');
    if (!papersList) return;

    const totalPages = Math.ceil(papers.length / papersPerPage);
    const startIdx = (currentPapersPage - 1) * papersPerPage;
    const endIdx = startIdx + papersPerPage;
    const papersToShow = papers.slice(startIdx, endIdx);

    // Render papers for current page with checkboxes
    const papersHTML = papersToShow.map((paper, idx) => {
        const globalIdx = startIdx + idx;
        const isChecked = selectedPapers.has(globalIdx) ? 'checked' : '';
        return `
            <div class="paper-item" style="background-color: white; border: 1px solid #dee2e6; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; display: flex; gap: 0.75rem;">
                <input type="checkbox" class="paper-checkbox" data-paper-idx="${globalIdx}" ${isChecked}
                    style="margin-top: 0.25rem; cursor: pointer;">
                <div style="flex: 1;">
                    <h5 style="margin-top: 0; margin-bottom: 0.5rem;">${paper.title} ${paper.year ? `(${paper.year})` : ''}</h5>
                    <p class="paper-summary" style="font-size: 0.9em; margin-bottom: 0.5rem;">${paper.summary}</p>
                    <div class="paper-links" style="font-size: 0.9em;">
                        ${paper.doi ? `<a href="https://doi.org/${paper.doi}" target="_blank" rel="noopener" style="margin-right: 1rem;">DOI</a>` : ''}
                        ${paper.url ? `<a href="${paper.url}" target="_blank" rel="noopener">View Paper</a>` : ''}
                    </div>
                </div>
            </div>
        `;
    }).join('');

    // Render pagination controls
    let paginationHTML = '';
    if (totalPages > 1) {
        const pageNumbers: number[] = [];
        // Show up to 5 page numbers around current page
        const maxPagesToShow = 5;
        let startPage = Math.max(1, currentPapersPage - Math.floor(maxPagesToShow / 2));
        let endPage = Math.min(totalPages, startPage + maxPagesToShow - 1);

        // Adjust if we're near the end
        if (endPage - startPage < maxPagesToShow - 1) {
            startPage = Math.max(1, endPage - maxPagesToShow + 1);
        }

        for (let i = startPage; i <= endPage; i++) {
            pageNumbers.push(i);
        }

        paginationHTML = `
            <div class="papers-pagination" style="display: flex; align-items: center; justify-content: center; gap: 0.5rem; margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #dee2e6;">
                <button id="papers-prev-btn" class="pagination-btn" ${currentPapersPage === 1 ? 'disabled' : ''}
                    style="padding: 0.5rem 1rem; background-color: ${currentPapersPage === 1 ? '#ccc' : '#007bff'}; color: white; border: none; border-radius: 4px; cursor: ${currentPapersPage === 1 ? 'not-allowed' : 'pointer'};">
                    Previous
                </button>
                <div class="page-numbers" style="display: flex; gap: 0.25rem;">
                    ${pageNumbers.map(pageNum => `
                        <button class="page-number-btn ${pageNum === currentPapersPage ? 'active' : ''}"
                            data-page="${pageNum}"
                            style="padding: 0.5rem 0.75rem; background-color: ${pageNum === currentPapersPage ? '#007bff' : '#f8f9fa'};
                            color: ${pageNum === currentPapersPage ? 'white' : '#333'}; border: 1px solid #dee2e6; border-radius: 4px;
                            cursor: pointer; min-width: 2.5rem;">
                            ${pageNum}
                        </button>
                    `).join('')}
                </div>
                <button id="papers-next-btn" class="pagination-btn" ${currentPapersPage === totalPages ? 'disabled' : ''}
                    style="padding: 0.5rem 1rem; background-color: ${currentPapersPage === totalPages ? '#ccc' : '#007bff'}; color: white; border: none; border-radius: 4px; cursor: ${currentPapersPage === totalPages ? 'not-allowed' : 'pointer'};">
                    Next
                </button>
                <span style="font-size: 0.9em; color: #666; margin-left: 0.5rem;">
                    Page ${currentPapersPage} of ${totalPages} (${papers.length} total)
                </span>
            </div>
        `;
    }

    papersList.innerHTML = papersHTML + paginationHTML;

    // Attach checkbox listeners for papers
    papersList.querySelectorAll('.paper-checkbox').forEach(checkbox => {
        checkbox.addEventListener('change', (e) => {
            const idx = parseInt((e.target as HTMLElement).getAttribute('data-paper-idx') || '-1');
            if (idx >= 0) {
                if ((e.target as HTMLInputElement).checked) {
                    selectedPapers.add(idx);
                } else {
                    selectedPapers.delete(idx);
                }
            }
        });
    });

    // Attach pagination event listeners
    const prevBtn = document.getElementById('papers-prev-btn');
    const nextBtn = document.getElementById('papers-next-btn');
    const pageNumberBtns = document.querySelectorAll('.page-number-btn');

    if (prevBtn) {
        prevBtn.addEventListener('click', () => {
            if (currentPapersPage > 1) {
                currentPapersPage--;
                renderPapersList(papers);
            }
        });
    }

    if (nextBtn) {
        nextBtn.addEventListener('click', () => {
            if (currentPapersPage < totalPages) {
                currentPapersPage++;
                renderPapersList(papers);
            }
        });
    }

    pageNumberBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const pageNum = parseInt((btn as HTMLElement).dataset.page || '1');
            if (pageNum !== currentPapersPage) {
                currentPapersPage = pageNum;
                renderPapersList(papers);
            }
        });
    });
}

async function handleRegenerateSummary(originalData: PIResearchData): Promise<void> {
    if (!currentPIResearch) {
        alert('No PI research data available');
        return;
    }

    const regenerateBtn = document.getElementById('regenerate-summary-btn') as HTMLButtonElement;
    if (!regenerateBtn) return;

    // Collect selected items
    const selectedPapersList: Paper[] = [];
    const selectedTrialsList: ClinicalTrial[] = [];
    const selectedNihProjectsList: NIHProject[] = [];

    if (currentPIResearch && currentPIResearch.papers) {
        selectedPapers.forEach(idx => {
            if (idx < currentPIResearch!.papers!.length) {
                selectedPapersList.push(currentPIResearch!.papers![idx]);
            }
        });
    }

    if (currentPIResearch && currentPIResearch.clinical_trials) {
        selectedTrials.forEach(idx => {
            if (idx < currentPIResearch!.clinical_trials!.length) {
                selectedTrialsList.push(currentPIResearch!.clinical_trials![idx]);
            }
        });
    }

    if (currentPIResearch && currentPIResearch.nih_projects) {
        selectedNihProjects.forEach(idx => {
            if (idx < currentPIResearch!.nih_projects!.length) {
                selectedNihProjectsList.push(currentPIResearch!.nih_projects![idx]);
            }
        });
    }

    // If nothing is selected, use all items
    const papersToUse = selectedPapersList.length > 0 ? selectedPapersList : (currentPIResearch?.papers || []);
    const trialsToUse = selectedTrialsList.length > 0 ? selectedTrialsList : (currentPIResearch?.clinical_trials || []);
    const nihProjectsToUse = selectedNihProjectsList.length > 0 ? selectedNihProjectsList : (currentPIResearch?.nih_projects || []);

    // Show loading
    regenerateBtn.disabled = true;
    regenerateBtn.textContent = 'Regenerating...';

    try {
        // Send data directly without extra wrapper - backend expects the structure directly
        const requestBody: any = {
            pi_info: currentPIResearch.pi_info,
            papers: papersToUse,
            clinical_trials: trialsToUse,
            nih_projects: nihProjectsToUse
        };

        const response = await fetch('/api/v1/pi-research/regenerate-summary', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(requestBody),
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.detail || 'Failed to regenerate summary');
        }

        const result = await response.json();

        // Update the PI summary
        const summaryContent = document.getElementById('pi-summary-content');
        if (summaryContent && result.pi_info && result.pi_info.summary) {
            const piInfoHTML = summaryContent.querySelector('.pi-info');
            if (piInfoHTML) {
                const summaryP = piInfoHTML.querySelector('p:last-child');
                if (summaryP) {
                    summaryP.textContent = result.pi_info.summary;
                } else {
                    // Add summary if it doesn't exist
                    piInfoHTML.innerHTML += `<p>${result.pi_info.summary}</p>`;
                }
            }
        }

        // Update currentPIResearch with new summary
        if (currentPIResearch) {
            currentPIResearch.pi_info.summary = result.pi_info?.summary || currentPIResearch.pi_info.summary;
        }

    } catch (error: any) {
        console.error('Error regenerating summary:', error);
        alert(`Error: ${error.message}`);
    } finally {
        regenerateBtn.disabled = false;
        regenerateBtn.textContent = 'Regenerate Summary';
    }
}
